# Generated by Django 5.2.6 on 2025-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_user_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
