# Generated by Django 5.2.6 on 2025-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_alter_user_classes_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
