# Generated by Django 5.2.6 on 2025-09-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_alter_user_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes',
        ),
    ]
