# Generated by Django 5.2.6 on 2025-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0005_remove_user_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
