# Generated by Django 5.2.6 on 2025-09-18 08:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_notes_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('coefficent', models.IntegerField()),
            ],
            options={
                'ordering': ['-nom'],
            },
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note_time',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='noted',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='noted_by',
        ),
        migrations.AddField(
            model_name='notes',
            name='date_noted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notes',
            name='devoir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='devoirs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='interrogation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.classes'),
        ),
    ]
