# Generated by Django 5.2.6 on 2025-09-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_classes_remove_notes_note_time_remove_notes_noted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='etudiant_classes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='etudiants.user'),
            preserve_default=False,
        ),
    ]
