# Generated by Django 5.2.6 on 2025-09-18 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_classes_etudiant_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='etudiant_classes',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='etudiants.user'),
        ),
    ]
