# Generated by Django 5.2.6 on 2025-09-18 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0009_alter_classes_etudiant_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note',
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('SQL', 'SQL')], max_length=20)),
                ('interrogation', models.FloatField(blank=True, null=True)),
                ('devoir', models.FloatField(blank=True, null=True)),
                ('devoirs', models.FloatField(blank=True, null=True)),
                ('coefficent', models.PositiveIntegerField(default=1)),
                ('date_note', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='notes',
        ),
    ]
