# Generated by Django 5.2.6 on 2025-09-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0010_remove_notes_classes_remove_notes_note_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note',
            new_name='notes',
        ),
    ]
