# Generated by Django 5.2.6 on 2025-09-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0011_rename_note_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='etudiant',
            new_name='note',
        ),
    ]
