# Generated by Django 5.2.6 on 2025-09-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0012_rename_etudiant_notes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='matiere',
        ),
        migrations.AddField(
            model_name='user',
            name='matiere',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('SQL', 'SQL')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.user'),
        ),
    ]
