# Generated by Django 5.2.6 on 2025-09-22 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0013_remove_notes_matiere_user_matiere_alter_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='coefficent',
            new_name='coeff',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='devoirs',
            new_name='interrogation1',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='interrogation',
            new_name='interrogation2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matiere',
        ),
        migrations.AddField(
            model_name='notes',
            name='matiere',
            field=models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('SQL', 'SQL')], default='Django', max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_note',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
