# Generated by Django 5.2.6 on 2025-09-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0014_rename_coefficent_notes_coeff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='coeff',
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matieres', models.CharField(choices=[('Django', 'Django'), ('Python', 'Python'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('SQL', 'SQL')], max_length=20)),
                ('coefficients', models.PositiveIntegerField(default=1)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.user')),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.matiere'),
        ),
    ]
