# Generated by Django 5.2.6 on 2025-09-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0015_remove_notes_coeff_matiere_alter_notes_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='matiere',
        ),
    ]
