# Generated by Django 5.2.6 on 2025-09-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0016_remove_matiere_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date_note',
        ),
    ]
