# Generated by Django 5.2.6 on 2025-09-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0017_remove_notes_date_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='matiere',
        ),
    ]
