# Generated by Django 5.2.6 on 2025-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0018_remove_notes_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='matiere',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
