# Generated by Django 5.2.6 on 2025-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0019_notes_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='coefficients',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
