# Generated by Django 5.2.6 on 2025-09-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0020_notes_coefficients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
