# Generated by Django 5.2.6 on 2025-09-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0021_delete_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.user'),
        ),
    ]
